--[[ HQMeta: plot-local bounding-box centre (c) and size (s) of every imported HQ
mesh, keyed by mesh name. The children are GENERATED by the Blender scripts
(V1 by blender/hq.py, V2 by blender/hq2.py, through blender/metafile.py), which
merge each run into them, so a rebuilt mesh never needs hand-pasting again.
CampusArch.skinHQ reads this. ]]
local t = {}
for _, n in ipairs({ "V1", "V2" }) do
	for k, v in pairs(require(script:WaitForChild(n))) do
		t[k] = v
	end
end
return t
