--[[
	Downtown (v4.0) -- the city at the east end of the valley, rebuilt.

	His note: "the city in the back still looks trash." It was eight grey boxes
	with glass strips, and five of them stood PAST the valley's walkable edge
	(x ~786) on the hillside, over no ground at all. Now the main road ends at a
	roundabout on a paved downtown plaza (x 620-790), inside the valley, and
	the buildings are the Blender set (blender/city2.py), in the HQ's language:

	  THE RESIDENCES   (668, 64)  apartments. Its lobby has a sales desk and the
	                               residents' lift; each owner's unit is a REAL
	                               floor of this tower (Apartments.lua).
	  VALLEY MOTORS    (664, -62) the car dealership (Cars.lua)
	  the spire        (768, 0)   the landmark at the end of the road
	  the stack        (740, 70)
	  the stepped tower(742, -68)

	Everything a player can touch has box collision (the meshes never collide).
	Missing meshes = nothing breaks: the building is simply absent.
]]
local RS = game:GetService("ReplicatedStorage")

local Downtown = {}

-- generated by blender/city2.py (bbox centre relative to the building origin, size)
local META = {
	Dealer_Showroom = { c = Vector3.new(-0.000, 8.300, 5.600), s = Vector3.new(80.000, 22.600, 64.800) },  -- 1836 tris
	Dealer_Showroom_Glass = { c = Vector3.new(-0.000, 7.900, 4.892), s = Vector3.new(71.609, 13.400, 33.824) },  -- 192 tris
	Residences_Tower = { c = Vector3.new(-0.000, 104.000, 2.750), s = Vector3.new(55.000, 214.000, 52.300) },  -- 34032 tris
	Residences_Tower_Glass = { c = Vector3.new(-0.000, 101.100, 0.000), s = Vector3.new(49.609, 199.400, 46.400) },  -- 8256 tris
	Tower_Spire = { c = Vector3.new(-0.000, 110.500, 0.000), s = Vector3.new(39.000, 227.000, 39.000) },  -- 28516 tris
	Tower_Spire_Glass = { c = Vector3.new(-0.000, 91.350, 0.000), s = Vector3.new(33.609, 179.900, 33.609) },  -- 8700 tris
	Tower_Stack = { c = Vector3.new(-0.298, 68.250, 0.272), s = Vector3.new(46.298, 142.500, 38.630) },  -- 22784 tris
	Tower_Stack_Glass = { c = Vector3.new(-0.347, 68.900, -0.108), s = Vector3.new(43.592, 132.800, 35.183) },  -- 6264 tris
	Tower_Stepped = { c = Vector3.new(-0.000, 81.000, 0.000), s = Vector3.new(51.000, 168.000, 41.000) },  -- 23372 tris
	Tower_Stepped_Glass = { c = Vector3.new(-0.000, 73.000, 0.000), s = Vector3.new(47.404, 138.600, 37.404) },  -- 7656 tris
}
Downtown.META = META

-- the plan (world). Front of every building = its local +Z.
Downtown.ROAD_END = 700                   -- the Kenney road stops here; the roundabout takes over
Downtown.ROUNDABOUT = Vector3.new(724, 0, 0)
Downtown.RES = CFrame.new(668, 0, 64) * CFrame.Angles(0, math.pi, 0)       -- faces the road (-Z)
Downtown.DEALER = CFrame.new(664, 0, -62)                                  -- faces the road (+Z)
Downtown.TOWERS = {
	{ name = "Tower_Spire", cf = CFrame.new(768, 0, 0) * CFrame.Angles(0, -math.pi / 2, 0), w = 34, d = 34, h = 214 },
	{ name = "Tower_Stack", cf = CFrame.new(740, 0, 70) * CFrame.Angles(0, math.pi, 0), w = 40, d = 32, h = 136 },
	{ name = "Tower_Stepped", cf = CFrame.new(742, 0, -68), w = 46, d = 36, h = 144 },
}
-- The Residences (blender/city2.py RES): 50 x 40, radius 7, lobby 14, 18 floors of 10
Downtown.RES_SIZE = { w = 50, d = 40, R = 7, lobby = 14, floor = 10, floors = 18 }
Downtown.DEALER_SIZE = { w = 72, d = 44, R = 10, h = 16 }
local PLAZA_Y = 0.8                -- level with the Kenney road tiles' top

local PAVING = Color3.fromRGB(206, 200, 188)
local PAVING_DARK = Color3.fromRGB(176, 170, 160)
local ASPHALT = Color3.fromRGB(62, 62, 66)
local STONE = Color3.fromRGB(196, 186, 170)
local CHARCOAL = Color3.fromRGB(38, 41, 48)
local WHITE = Color3.fromRGB(243, 239, 230)
local GLASS_TINT = Color3.fromRGB(132, 172, 190)

local function part(parent, props)
	local p = Instance.new("Part")
	p.Anchored = true
	p.TopSurface = Enum.SurfaceType.Smooth
	p.BottomSurface = Enum.SurfaceType.Smooth
	p.Material = Enum.Material.SmoothPlastic
	p.CastShadow = false
	for k, v in pairs(props) do p[k] = v end
	p.Parent = parent
	return p
end
Downtown.part = part

local function collider(parent, cf, size)
	return part(parent, { Name = "Collider", CFrame = cf, Size = size, Transparency = 1, CanQuery = false, CanTouch = false })
end

-- a mesh from ReplicatedStorage.SVMeshes, placed so its modelled origin sits on `cf`
local function placeMesh(name, cf, parent, glass)
	local lib = RS:FindFirstChild("SVMeshes")
	local t = lib and lib:FindFirstChild(name)
	local m = META[name]
	if not t or not m then return nil end
	local src = t:IsA("BasePart") and t or t:FindFirstChildWhichIsA("MeshPart", true)
	if not src then return nil end
	local p = src:Clone()
	p.Name = name
	p.PivotOffset = CFrame.new()
	p.Anchored = true
	p.CanCollide = false
	p.CanQuery = false
	p.CanTouch = false
	p.CFrame = cf * CFrame.new(m.c)
	if glass then
		p.Material = Enum.Material.Glass
		p.Color = GLASS_TINT
		p.Transparency = 0.45
		p.CastShadow = false
	else
		p.Color = Color3.new(1, 1, 1)
		p.CastShadow = true
	end
	p.Parent = parent
	return p
end
Downtown.placeMesh = placeMesh

-- a sign painted on a part's face
local function sign(board, face, text, color, font)
	local sg = Instance.new("SurfaceGui")
	sg.Face = face or Enum.NormalId.Back
	sg.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
	sg.PixelsPerStud = 32
	sg.LightInfluence = 0
	sg.MaxDistance = 400
	sg.Parent = board
	local t = Instance.new("TextLabel")
	t.BackgroundTransparency = 1
	t.Size = UDim2.new(0.92, 0, 0.7, 0)
	t.Position = UDim2.new(0.04, 0, 0.15, 0)
	t.TextScaled = true
	t.FontFace = font or Font.new("rbxasset://fonts/families/Montserrat.json", Enum.FontWeight.Bold)
	t.TextColor3 = color or WHITE
	t.Text = text
	t.Parent = sg
	return t
end
Downtown.sign = sign

local function tree(parent, pos, height)
	local lib = RS:FindFirstChild("SVMeshes")
	local pick = { "Oak_A", "Oak_B", "Eucalypt_A" }
	local name = pick[math.random(1, #pick)]
	-- v4.1: the low-poly stand-in when it is imported
	local vgm = game:GetService("ServerScriptService"):FindFirstChild("ValleyGen")
	local okv, vg = pcall(function() return vgm and require(vgm) end)
	local t = (okv and vg and vg.lpTemplate and vg.lpTemplate(name)) or (lib and lib:FindFirstChild(name))
	if not t then return end
	local src = t:IsA("BasePart") and t or t:FindFirstChildWhichIsA("MeshPart", true)
	if not src then return end
	local p = src:Clone()
	p.PivotOffset = CFrame.new()
	p.Anchored = true
	p.CanCollide = false
	p.CanQuery = false
	p.CanTouch = false
	p.CastShadow = true
	p.Color = Color3.new(1, 1, 1)
	local k = height / p.Size.Y
	p.Size = p.Size * k
	p.CFrame = CFrame.new(pos + Vector3.new(0, p.Size.Y / 2, 0)) * CFrame.Angles(0, math.random() * 6.28, 0)
	p.Parent = parent
	return p
end

function Downtown.build(world)
	local f = Instance.new("Folder")
	f.Name = "Downtown"
	f.Parent = world
	Downtown.folder = f

	-- 1. the plaza: paving over the whole flat end of the valley, a darker border
	part(f, { Name = "Plaza", Size = Vector3.new(172, 0.8, 196), CFrame = CFrame.new(706, PLAZA_Y - 0.4, 0),
		Color = PAVING, Material = Enum.Material.Pavement })
	part(f, { Name = "PlazaEdge", Size = Vector3.new(176, 0.7, 200), CFrame = CFrame.new(706, PLAZA_Y - 0.5, 0),
		Color = PAVING_DARK, Material = Enum.Material.Concrete, CanQuery = false })
	-- the road from the end of the Kenney tiles to the roundabout
	local rb = Downtown.ROUNDABOUT
	part(f, { Name = "DowntownRoad", Size = Vector3.new(rb.X - Downtown.ROAD_END + 2, 0.3, 26), CFrame = CFrame.new((Downtown.ROAD_END + rb.X) / 2 - 1, PLAZA_Y + 0.02, 0),
		Color = ASPHALT, Material = Enum.Material.Asphalt })
	-- the roundabout: asphalt ring, a kerbed island with a fountain and a tree
	part(f, { Name = "Roundabout", Shape = Enum.PartType.Cylinder, Size = Vector3.new(0.32, 50, 50),
		CFrame = CFrame.new(rb + Vector3.new(0, PLAZA_Y + 0.03, 0)) * CFrame.Angles(0, 0, math.rad(90)), Color = ASPHALT, Material = Enum.Material.Asphalt })
	part(f, { Name = "IslandKerb", Shape = Enum.PartType.Cylinder, Size = Vector3.new(1.0, 20, 20),
		CFrame = CFrame.new(rb + Vector3.new(0, PLAZA_Y + 0.4, 0)) * CFrame.Angles(0, 0, math.rad(90)), Color = STONE, Material = Enum.Material.Concrete })
	part(f, { Name = "Island", Shape = Enum.PartType.Cylinder, Size = Vector3.new(0.4, 18.6, 18.6),
		CFrame = CFrame.new(rb + Vector3.new(0, PLAZA_Y + 0.75, 0)) * CFrame.Angles(0, 0, math.rad(90)), Color = Color3.fromRGB(122, 170, 86), Material = Enum.Material.LeafyGrass, CanCollide = false })
	part(f, { Name = "FountainBowl", Shape = Enum.PartType.Cylinder, Size = Vector3.new(1.6, 9, 9),
		CFrame = CFrame.new(rb + Vector3.new(0, PLAZA_Y + 1.4, 0)) * CFrame.Angles(0, 0, math.rad(90)), Color = STONE, Material = Enum.Material.Concrete })
	part(f, { Name = "FountainWater", Shape = Enum.PartType.Cylinder, Size = Vector3.new(0.2, 8, 8),
		CFrame = CFrame.new(rb + Vector3.new(0, PLAZA_Y + 2.1, 0)) * CFrame.Angles(0, 0, math.rad(90)), Color = Color3.fromRGB(96, 170, 214),
		Material = Enum.Material.Glass, Transparency = 0.2, CanCollide = false })
	local jet = part(f, { Name = "FountainJet", Size = Vector3.new(0.6, 0.6, 0.6), CFrame = CFrame.new(rb + Vector3.new(0, PLAZA_Y + 2.3, 0)),
		Transparency = 1, CanCollide = false, CanQuery = false })
	local pe = Instance.new("ParticleEmitter")
	pe.Texture = "rbxasset://textures/particles/sparkles_main.dds"
	pe.Color = ColorSequence.new(Color3.fromRGB(220, 240, 255))
	pe.LightEmission = 0.4
	pe.Size = NumberSequence.new({ NumberSequenceKeypoint.new(0, 0.5), NumberSequenceKeypoint.new(1, 0.2) })
	pe.Transparency = NumberSequence.new({ NumberSequenceKeypoint.new(0, 0.2), NumberSequenceKeypoint.new(1, 1) })
	pe.Lifetime = NumberRange.new(1.0, 1.3)
	pe.Rate = 60
	pe.Speed = NumberRange.new(14, 16)
	pe.SpreadAngle = Vector2.new(8, 8)
	pe.Acceleration = Vector3.new(0, -28, 0)
	pe.EmissionDirection = Enum.NormalId.Top
	pe.Parent = jet
	-- crossing lines on the approach and a kerb round the plaza's road edges
	for k = 0, 6 do
		part(f, { Name = "Crossing", Size = Vector3.new(1.2, 0.05, 22), CFrame = CFrame.new(Downtown.ROAD_END + 4 + k * 2.2, PLAZA_Y + 0.2, 0),
			Color = WHITE, CanCollide = false, CanQuery = false })
	end

	-- the Kenney road tiles are visual only (no collision, no query) and sit 0.8
	-- over the flat ground, so wheels and feet sank into them. An invisible deck
	-- at their top along the main road and the two cross streets fixes both.
	local function deck(cx, cz, sx, sz)
		part(f, { Name = "RoadDeck", Size = Vector3.new(sx, 1, sz), CFrame = CFrame.new(cx, 0.3, cz), Transparency = 1, CanTouch = false })
	end
	--[[ v9: the deck used to start at x -585 and run the whole width of the map,
	so an invisible 1285-stud collision slab lay straight across what is now the
	central park. It starts at the outer ring road and runs east. ]]
	local hub = game:GetService("ServerScriptService"):FindFirstChild("CampusHub")
	local okH, HUB = pcall(function() return hub and require(hub) end)
	local x0 = ((okH and HUB and HUB.R_ROAD_OUT) or 596) - 10
	deck((x0 + Downtown.ROAD_END) / 2, 0, Downtown.ROAD_END - x0, 50)
	local ck = game:GetService("ServerScriptService"):FindFirstChild("CityKit")
	local okC, CK = pcall(function() return ck and require(ck) end)
	local crossLen = (okC and CK and CK.CROSS_LEN) or 250
	for _, cx in ipairs((okC and CK and CK.CROSS_X) or { -185, 165 }) do
		deck(cx, 0, 50, 2 * crossLen + 30)
	end

	-- 2. the buildings
	-- (a building whose mesh is missing is simply not there: no invisible walls)
	local res = Downtown.RES
	local hasRes = placeMesh("Residences_Tower", res, f) ~= nil
	placeMesh("Residences_Tower_Glass", res, f, true)
	local hasDealer = placeMesh("Dealer_Showroom", Downtown.DEALER, f) ~= nil
	placeMesh("Dealer_Showroom_Glass", Downtown.DEALER, f, true)
	for _, t in ipairs(Downtown.TOWERS) do
		if placeMesh(t.name, t.cf, f) then
			placeMesh(t.name .. "_Glass", t.cf, f, true)
			collider(f, t.cf * CFrame.new(0, t.h / 2, 0), Vector3.new(t.w, t.h, t.d))
		end
	end
	if not hasRes then warn("[SV] downtown: Residences mesh missing") end

	-- 3. The Residences: the tower above the lobby is solid; the lobby is a room
	local HQF = game:GetService("ServerScriptService"):FindFirstChild("HQFloors")
	local okH, hq = pcall(function() return HQF and require(HQF) end)
	local R = Downtown.RES_SIZE
	if hasRes then
	local g = function(x, y, z) return res * CFrame.new(x, y, z) end
	-- no solid box above the lobby: the apartments are real floors of this tower
	-- (each owner's unit brings its own floor and walls, Apartments.buildUnit)
	local function add(props)
		local p = part(f, props)
		return p
	end
	if okH and hq and hq.envelope then
		hq.envelope(add, g, R.w, R.d, R.R, 1.4, R.lobby, 6.2)
	end
	add({ Name = "LobbyFloor", Size = Vector3.new(R.w - 2, 0.2, R.d - 2), CFrame = g(0, 1.3, 0), Color = Color3.fromRGB(214, 206, 192), Material = Enum.Material.Marble })
	add({ Name = "LobbyCeiling", Size = Vector3.new(R.w - 4, 0.2, R.d - 4), CFrame = g(0, R.lobby - 0.8, 0), Color = Color3.fromRGB(240, 236, 228), CanCollide = false })
	-- the residents' lift at the back, the sales desk on the left, a lounge on the right
	local liftCore = add({ Name = "ResLiftCore", Size = Vector3.new(12, R.lobby - 1.6, 3), CFrame = g(0, 1.4 + (R.lobby - 1.6) / 2, -R.d / 2 + 2.4), Color = WHITE })
	add({ Name = "ResLiftDoors", Size = Vector3.new(5.2, 8, 0.2), CFrame = g(0, 5.4, -R.d / 2 + 4), Color = Color3.fromRGB(176, 178, 184), Material = Enum.Material.Metal, CanCollide = false })
	local liftBtn = add({ Name = "ResLiftButton", Size = Vector3.new(0.5, 0.9, 0.2), CFrame = g(3.6, 5.6, -R.d / 2 + 4), Color = CHARCOAL, CanCollide = false })
	Downtown.resLiftButton = liftBtn
	Downtown.resLobbyStand = g(0, 1.5, -R.d / 2 + 8) * CFrame.Angles(0, math.pi, 0)
	Downtown.resStreetStand = g(0, 1.5, R.d / 2 + 10)
	local desk = add({ Name = "SalesDesk", Size = Vector3.new(8, 3, 2.4), CFrame = g(-14, 2.9, 4), Color = Color3.fromRGB(150, 108, 72), Material = Enum.Material.WoodPlanks })
	add({ Name = "SalesDeskTop", Size = Vector3.new(8.6, 0.3, 3), CFrame = g(-14, 4.55, 4), Color = WHITE })
	Downtown.salesDesk = desk
	local board = add({ Name = "SalesSign", Size = Vector3.new(10, 2.2, 0.3), CFrame = g(-14, 9.5, -R.d / 2 + 1.2), Color = CHARCOAL, CanCollide = false })
	sign(board, Enum.NormalId.Back, "APARTMENTS  ·  FOR SALE", Color3.fromRGB(255, 208, 70))
	-- the name on the canopy's sign board (city2.py: hd + 8.6..8.9, y 9.6..11.4, 18 wide)
	local nameBoard = add({ Name = "ResName", Size = Vector3.new(18, 1.8, 0.2), CFrame = g(0, 10.5, R.d / 2 + 9.0), Color = CHARCOAL, CanCollide = false })
	sign(nameBoard, Enum.NormalId.Back, "THE RESIDENCES")
	local okF, FK = pcall(function() return require(RS:WaitForChild("FurnitureKit", 5)) end)
	if not okF then FK = nil end
	for _, k in ipairs({ "loungeDesignSofa", "pottedPlant", "lampSquareFloor" }) do
		if FK and FK.has and FK.has(k) then
			if k == "loungeDesignSofa" then
				FK.put(k, g(14, 1.4, 2), f, { yaw = -90 })
				FK.put(k, g(18, 1.4, -6), f, { yaw = 0 })
			elseif k == "pottedPlant" then
				FK.put(k, g(20, 1.4, 10), f, {})
				FK.put(k, g(-20, 1.4, 12), f, {})
			else
				FK.put(k, g(20, 1.4, -2), f, {})
			end
		end
	end

	end

	-- 4. Valley Motors: showroom walls and a door, its sign, the display pads
	if hasDealer then
	local D = Downtown.DEALER_SIZE
	local dg = function(x, y, z) return Downtown.DEALER * CFrame.new(x, y, z) end
	local function dadd(props) return part(f, props) end
	if okH and hq and hq.envelope then
		hq.envelope(dadd, dg, D.w, D.d, D.R, 1.0, D.h - 1.4, 6.5)
	end
	collider(f, dg(0, (D.h - 1.4) / 2, -D.d / 2 + 7.5), Vector3.new(D.w - 2, D.h - 1.4, 13))       -- the service block
	dadd({ Name = "ShowroomFloor", Size = Vector3.new(D.w - 3, 0.2, D.d - 16), CFrame = dg(0, 1.1, 6.5), Color = Color3.fromRGB(46, 50, 58),
		Material = Enum.Material.Marble, Reflectance = 0.08 })
	local dBoard = dadd({ Name = "DealerName", Size = Vector3.new(31.6, 2.6, 0.2), CFrame = dg(0, D.h + 2.25, D.d / 2 + 5.3), Color = CHARCOAL, CanCollide = false })
	sign(dBoard, Enum.NormalId.Back, "VALLEY MOTORS")
	-- a pylon sign by the road
	local pylon = dadd({ Name = "DealerPylon", Size = Vector3.new(3, 18, 3), CFrame = dg(D.w / 2 - 2, 9 + 0.4, D.d / 2 + 16), Color = CHARCOAL })
	sign(pylon, Enum.NormalId.Back, "VM", Color3.fromRGB(255, 208, 70), Font.new("rbxasset://fonts/families/FredokaOne.json"))
	Downtown.dealerPads = {}
	for i, o in ipairs({ { -24, 10 }, { -8, 14 }, { 8, 14 }, { 24, 10 }, { 0, 1 } }) do
		local pad = dadd({ Name = "DisplayPad" .. i, Shape = Enum.PartType.Cylinder, Size = Vector3.new(0.4, 13, 13),
			CFrame = dg(o[1], 1.3, o[2]) * CFrame.Angles(0, 0, math.rad(90)),
			Color = i == 5 and Color3.fromRGB(230, 226, 218) or Color3.fromRGB(70, 74, 84), Material = Enum.Material.SmoothPlastic })
		Downtown.dealerPads[i] = dg(o[1], 1.5, o[2]) * CFrame.Angles(0, math.rad(i == 5 and 0 or (o[1] < 0 and 30 or -30)), 0)
		local _ = pad
	end
	-- the forecourt where a bought car waits
	-- in the plaza between the showroom and the sidewalk (on the sidewalk, the
	-- ambient cyclists rode straight through a new car during its reveal),
	-- centred between the two tree planters at x 630 / 650
	Downtown.dealerForecourt = Downtown.DEALER * CFrame.new(-24, 0.8, D.d / 2 + 8) * CFrame.Angles(0, math.rad(90), 0)
	end

	-- 5. street trees in raised planters, lamps and benches round the plaza
	for _, p in ipairs({ { 630, 30 }, { 650, 30 }, { 690, 30 }, { 710, 30 }, { 630, -30 }, { 650, -30 }, { 690, -30 }, { 710, -30 },
		{ 760, 34 }, { 760, -34 }, { 700, 96 }, { 620, 96 }, { 704, -94 }, { 624, -94 } }) do
		part(f, { Name = "TreePlanter", Size = Vector3.new(4, 1.2, 4), CFrame = CFrame.new(p[1], PLAZA_Y + 0.6, p[2]), Color = STONE, Material = Enum.Material.Concrete })
		tree(f, Vector3.new(p[1], PLAZA_Y + 1.1, p[2]), 13)
	end
	for _, p in ipairs({ { 670, 28 }, { 670, -28 }, { 740, 24 }, { 740, -24 } }) do
		local bench = part(f, { Name = "Bench", Size = Vector3.new(6, 0.5, 1.8), CFrame = CFrame.new(p[1], PLAZA_Y + 1.4, p[2]), Color = Color3.fromRGB(150, 108, 72), Material = Enum.Material.WoodPlanks })
		part(f, { Name = "BenchBase", Size = Vector3.new(5, 1.2, 1.2), CFrame = CFrame.new(p[1], PLAZA_Y + 0.6, p[2]), Color = CHARCOAL })
		local _ = bench
	end
	return f
end

return Downtown
