--[[ WaferPlan: the Wafers HQ as pure data and rules (phase 1 of
docs/superpowers/specs/2026-09-30-wafers-hq-design.md).

No services, no requires: tests/offline runs it in Lune. The price, money and
staff-cap tables below are GENERATED from sim/wafer_plan.py (the simulator
that tuned them to the spec's targets); tests/offline/wafer.spec.luau checks
every number and rule here against the sim's golden file, so the game and the
sim can't drift. Change a number in the sim, re-fit, then run
`python sim/wafer_plan.py lua` and `python sim/wafer_plan.py golden`.

One level is one piece: L1 the garage, L2-17 wafer 1 (L2 the Lobby), L18
garden deck 1, L19-42 wafer 2, L43 deck 2, L44-67 wafer 3, L68 deck 3, L69-92
wafer 4, L93 roof garden, L94-97 the founder pavilion, L98-100 the crown.
Below your record, one BUILD tap rebuilds the rest of that storey at REBUILD
of the price. Not wired into the game yet (phase 3). ]]
local W = {}

W.MAX = 100
W.BLUEPRINT = { 18, 30, 43, 55, 68, 80, 93, 100 }   -- the highest level company n+1 may build
W.STAR_AT, W.GENIUS_AT, W.CAR_AT, W.PHONE_AT, W.SERIES_AT = 5, 9, 5, 5, 13
W.APT_FROM = { 5, 9, 13 }                           -- home k is for sale from this level
local APT_GATE = { { 9, 1 }, { 13, 2 }, { 18, 3 } }  -- building this level needs this many homes

-- BEGIN GENERATED by sim/wafer_plan.py (python wafer_plan.py lua): do not edit by hand
W.REBUILD = 0.025
W.BASE = { 0, 60, 111, 205, 759, 702, 1300, 2405, 8899, 8232, 15229, 28175, 104248, 96429, 178395, 330031, 610558, 2259065, 1169066, 1209983, 1252333, 1296165, 1341530, 1388484, 1437081, 1487379, 1539437, 1593317, 1649083, 1706801, 1766539, 1828368, 1892361, 1958594, 2027145, 2098095, 2171528, 2247532, 2326195, 2407612, 2491878, 2579094, 5338726, 2762790, 2859488, 2959570, 3063155, 3170365, 3281328, 3396175, 3515041, 3638067, 3765400, 3897189, 4033590, 4174766, 4320883, 4472114, 4628638, 4790640, 4958313, 5131854, 5311468, 5497370, 5689778, 5888920, 6095032, 12616717, 6529151, 6757671, 6994190, 7238986, 7492351, 7754583, 8025994, 8306904, 8597645, 8898563, 9210012, 9532363, 9865996, 10211306, 10568701, 10938606, 11321457, 11717708, 12127828, 12552302, 12991632, 13446340, 13916961, 14404055, 29816395, 15429984, 15970033, 16528985, 17107499, 17706262, 18325981, 37934781 }
W.MULT = { 1.0, 1.0, 1.0, 1.0, 1.6, 1.6, 1.6, 1.6, 2.6, 2.6, 2.6, 2.6, 4.2, 4.2, 4.2, 4.2, 4.2, 7.0, 7.07, 7.1407, 7.212107000000001, 7.28422807, 7.357070350700001, 7.430641054207001, 7.504947464749071, 7.579996939396562, 7.655796908790526, 7.732354877878432, 7.809678426657216, 7.887775210923788, 7.9666529630330265, 8.046319492663358, 8.12678268758999, 8.208050514465892, 8.290131019610548, 8.373032329806655, 8.456762653104722, 8.541330279635769, 8.626743582432127, 8.713011018256449, 8.800141128439012, 8.888142539723404, 11.221279956400796, 11.333492755964805, 11.446827683524454, 11.561295960359697, 11.676908919963296, 11.793678009162928, 11.911614789254557, 12.030730937147103, 12.151038246518572, 12.27254862898376, 12.395274115273596, 12.519226856426332, 12.644419124990598, 12.7708633162405, 12.898571949402909, 13.027557668896936, 13.157833245585906, 13.289411578041765, 13.422305693822183, 13.556528750760407, 13.69209403826801, 13.829014978650688, 13.967305128437197, 14.106978179721569, 14.248047961518784, 17.988160551417465, 18.16804215693164, 18.34972257850096, 18.533219804285967, 18.718552002328824, 18.90573752235212, 19.09479489757564, 19.285742846551393, 19.47860027501691, 19.67338627776708, 19.87012014054475, 20.068821341950198, 20.269509555369698, 20.472204650923395, 20.676926697432627, 20.883695964406957, 21.092532924051028, 21.303458253291538, 21.51649283582445, 21.731657764182696, 21.948974341824528, 22.168464085242768, 22.390148726095198, 22.61405021335615, 22.84019071548971, 28.835740778305755, 29.124098186088823, 29.415339167949703, 29.709492559629204, 30.006587485225495, 30.306653360077753, 30.60971989367853, 38.64477136576915 }
W.CAP = { 8, 8, 8, 8, 14, 14, 14, 14, 20, 20, 20, 20, 26, 26, 26, 26, 26, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 36, 36, 36, 36, 36, 38, 38, 40 }
-- END GENERATED

-- ---------------------------------------------------------------- the shape
--[[ One geometry, shared with blender/wafers.py (the mesh kit) so meshes and
collision agree. Plot-local studs: the garage stays at the origin, +Z faces the
road. Storey s of the building has its floor TOP at FLOOR_Y + s * H (storey 0's
slab sits on the plot floor). Every wafer is a ring DEPTH deep: segments are 45
degrees each, segment 1 centred on +Z (the road), then clockwise seen from
above (CFrame.Angles(0, (seg - 1) * 45deg, 0) turns +Z toward +X). ]]
W.GEO = {
	H = 13, SLAB = 1.5, FLOOR_Y = 1.0, DEPTH = 20,
	--[[ THE LEAN (v7). The old numbers were r 60, 64, 58, 54 with centres that
	zig-zagged +8x, -6x, +3x: wafer 2 was BIGGER than wafer 1 and the stack
	swung both ways, which is why it read as a pile rather than a building.

	Samsung's San Jose HQ -- the building this is named after -- is three
	stacked "wafers" of office separated by open garden floors, with 180ft
	cantilevered trusses. The silhouette works because the steps are even and
	the overhang goes ONE way.

	So: radius -4 per wafer, centre +6x -4z per wafer. Both constant. The lean
	vector is 7.2 studs per step, so the leading edge reaches 3.2 further out
	each time (a real cantilever) while the trailing edge sets back 11 (a deep
	shadowed underside). Over ~182 studs of height that is an 8.7 degree lean:
	readable from the plaza, nowhere near falling over.

	The lift core stays vertical at (0, -26). Gaps from the core to each ring
	are 14.0, 13.2, 10.4, 5.2 -- all positive, and bridgeBetween stretches the
	bridge mesh to whatever the gap is. ]]
	-- CONCENTRIC (reported 4 Oct: "the offset of the building is super bad").
	-- The stagger above was a deliberate 8.7-degree cantilever. Measured on a
	-- real save at wafer 2: the upper stack sat 6 studs east and 4 north of its
	-- own base, so one side overhung by 2 and the other set back by 10 -- at
	-- this size that does not read as a cantilever, it reads as the top half
	-- having slid off. The rings still step 60/56/52/48, which is where the
	-- taper comes from. Put the offsets back here if the lean is ever wanted.
	WAFER = {
		[1] = { cx = 0, cz = 0, r = 60 },      -- round the garage: the courtyard is 80 across
		[2] = { cx = 0, cz = 0, r = 56 },
		[3] = { cx = 0, cz = 0, r = 52 },
		[4] = { cx = 0, cz = 0, r = 48 },
	},
	CORE = { x = 0, z = -26, r = 6 },          -- the glass lift, in the courtyard behind the garage
	PAVILION = { rin = 36, rout = 44 },         -- on wafer 4's roof, 4 quarter pieces
}

-- ---------------------------------------------------------------- the plan
local SEG_ORDER = { 1, 2, 8, 3, 7, 4, 6, 5 }       -- segment 1 faces the road, then round both sides
local WAFERS = { { 1, { 0, 1 } }, { 2, { 3, 4, 5 } }, { 3, { 7, 8, 9 } }, { 4, { 11, 12, 13 } } }
local DECK_STOREY = { [1] = 2, [2] = 6, [3] = 10 }

W.PIECES = {}
local function add(kind, wafer, storey, seg)
	table.insert(W.PIECES, { level = #W.PIECES + 1, kind = kind, wafer = wafer, storey = storey, seg = seg })
end
add("garage", 0, 0, 0)
for _, wf in ipairs(WAFERS) do
	local w, storeys = wf[1], wf[2]
	for _, st in ipairs(storeys) do
		for _, seg in ipairs(SEG_ORDER) do add("segment", w, st, seg) end
	end
	if DECK_STOREY[w] then add("deck", w, DECK_STOREY[w], 0) end
end
add("roof", 4, 14, 0)
for k = 1, 4 do add("pavilion", 4, 14, k) end
for _, kind in ipairs({ "halo", "lantern", "mast" }) do add(kind, 4, 15, 0) end
assert(#W.PIECES == W.MAX, "the Wafers plan must have exactly 100 pieces")

-- ---------------------------------------------------------------- departments
W.DEPTS = {
	lobby = { seats = 2, fit = { engineer = true, research = true }, min = 2 },
	eng = { seats = 2, fit = { engineer = true, research = true }, min = 3 },
	studio = { seats = 2, fit = { designer = true }, min = 3 },
	cafe = { seats = 4, fit = { sales = true, recruiter = true }, min = 3 },
	servers = { seats = 0, fit = {}, min = 3 },
	labs = { seats = 2, fit = { research = true }, min = 19 },
	board = { seats = 0, fit = {}, min = 69 },
}
W.CHOOSABLE = { "eng", "studio", "cafe", "servers", "labs", "board" }
local QUALITY_FIRST, QUALITY_STEP = 0.25, 0.10
local MORALE_FIRST, MORALE_STEP = 0.20, 0.08
W.QUALITY_CAP, W.MORALE_CAP = 1.5, 0.8
W.LABS_WORK = 0.15            -- each AI Labs segment: products 15% faster
W.BOARD_INTEREST = 1          -- a Boardroom: investors start one interest higher

local function clampLevel(level) return math.clamp(math.floor(level or 1), 1, W.MAX) end

-- the departments you may choose for the segment at `level` ({} for fixed pieces)
function W.allowed(level)
	level = clampLevel(level)
	if W.PIECES[level].kind ~= "segment" then return {} end
	if level == 2 then return { "lobby" } end
	local out = {}
	for _, d in ipairs(W.CHOOSABLE) do
		if W.DEPTS[d].min <= level then table.insert(out, d) end
	end
	return out
end

-- what the built departments add: counts = { eng = 3, studio = 1, ... }
function W.effects(counts)
	local s, c = counts.studio or 0, counts.cafe or 0
	local q = s > 0 and math.min(W.QUALITY_CAP, QUALITY_FIRST + QUALITY_STEP * (s - 1)) or 0
	local m = c > 0 and math.min(W.MORALE_CAP, MORALE_FIRST + MORALE_STEP * (c - 1)) or 0
	return { quality = q, morale = m, compute = counts.servers or 0, labs = counts.labs or 0, board = counts.board or 0 }
end

-- seats the departments add (the garage's one seat is not counted here)
function W.seats(counts)
	local n = 0
	for d, k in pairs(counts) do
		local dept = W.DEPTS[d]
		if dept then n += dept.seats * k end
	end
	return n
end

-- how many homes you must own to build `level`
function W.aptRequired(level)
	local need = 0
	for _, g in ipairs(APT_GATE) do
		if level >= g[1] then need = g[2] end
	end
	return need
end

-- the highest level a company may build after `spins` spin-offs
function W.blueprint(spins)
	return W.BLUEPRINT[math.clamp(math.floor(spins or 0) + 1, 1, #W.BLUEPRINT)]
end

-- the guide's pick for the segment at `level` (the player can change it)
function W.recommend(level, counts, freeSeats)
	local opts = W.allowed(level)
	if #opts == 1 and opts[1] == "lobby" then return "lobby" end
	local has = {}
	for _, d in ipairs(opts) do has[d] = true end
	for _, d in ipairs({ "studio", "cafe", "servers", "labs", "board" }) do   -- show each department once
		if has[d] and (counts[d] or 0) == 0 then return d end
	end
	if freeSeats <= 1 then return "eng" end
	local e = W.effects(counts)
	if e.quality < W.QUALITY_CAP and (counts.studio or 0) <= (counts.cafe or 0) then return "studio" end
	if e.morale < W.MORALE_CAP then return "cafe" end
	if has.labs and (counts.labs or 0) * 2 < (counts.eng or 0) then return "labs" end
	if (counts.servers or 0) < level // 12 then return "servers" end
	return "eng"
end

--[[ HOW FAR EACH PATH'S GLASS STANDS INSIDE THE SLAB EDGE.

	The Dome puts its glass seven studs in, under the canopy overhang -- that
	recess IS the Dome. The Wafers and the Terrafab glaze at the slab edge.

	It lives here because three separate things need it and they were not
	agreeing: dome.py builds the mesh with it, Wafers.lua must lay furniture
	inside it, and SVCheck has to be able to assert that nothing crossed it.
	Furniture was placed for twenty studs of room in a thirteen-stud room for
	exactly as long as this number existed only in the Blender script.

	Keep in step with INSET in blender/dome.py. ]]
W.INSET = { W_ = 0.0, T_ = 0.0, D_ = 7.0 }
W.GLASS_BAND = 0.9                 -- glass + mullions, inboard of the inset line

-- ---------------------------------------------------------------- the numbers
function W.capAt(level) return W.CAP[clampLevel(level)] end
function W.multAt(level) return W.MULT[clampLevel(level)] end
function W.basePrice(level) return W.BASE[clampLevel(level)] end

-- a piece's price in a company: its base x the company's scale (Progression.runScale),
-- and REBUILD of that at or below the record the company started with
function W.price(level, scale, record)
	local v = W.basePrice(level) * scale
	if level <= record then v *= W.REBUILD end
	return math.floor(v)
end

-- a rebuild buys the rest of a storey in one tap: from `level` to the last piece on the same
-- wafer storey still at or below `record` (a deck or crown piece is one piece; above the
-- record a new piece is bought alone)
function W.rebuildLast(level, record)
	if level > record then return level end
	local first = W.PIECES[clampLevel(level)]
	if first.kind ~= "segment" then return level end
	local last = level
	while last + 1 <= math.min(record, W.MAX) do
		local nxt = W.PIECES[last + 1]
		if nxt.kind ~= "segment" or nxt.wafer ~= first.wafer or nxt.storey ~= first.storey then break end
		last += 1
	end
	return last
end

-- what the next BUILD tap costs: one new piece, or a rebuilt storey (each at REBUILD)
function W.batchPrice(level, scale, record)
	local total = 0
	for L = level, W.rebuildLast(level, record) do total += W.price(L, scale, record) end
	return total
end

return W
