--[[ generated by blender/lp_world.py (v4.1): the low-poly valley.
Children (ModuleScripts): Trees1, Trees2, Grid1, Grid2 -- a source is capped at 200,000
characters, so the trees and the vertex grid are split across them. ]]
local d = {
	facet = 40, water = -1.6,
	tiles = {
		LP_0_0 = { c = Vector3.new(-2155.56, 287.22, -1954.34), s = Vector3.new(488.89, 75.68, 491.31) },  -- 288 tris
		LP_0_1 = { c = Vector3.new(-2154.20, 279.31, -1480.23), s = Vector3.new(491.61, 91.68, 502.38) },  -- 288 tris
		LP_0_2 = { c = Vector3.new(-2154.20, 227.37, -1000.52), s = Vector3.new(491.59, 145.59, 499.98) },  -- 288 tris
		LP_0_3 = { c = Vector3.new(-2155.67, 159.65, -520.97), s = Vector3.new(488.65, 29.99, 500.15) },  -- 288 tris
		LP_0_4 = { c = Vector3.new(-2154.31, 163.17, -40.27), s = Vector3.new(491.38, 37.87, 501.30) },  -- 288 tris
		LP_0_5 = { c = Vector3.new(-2154.06, 161.01, 440.52), s = Vector3.new(491.88, 48.45, 501.03) },  -- 288 tris
		LP_0_6 = { c = Vector3.new(-2155.56, 176.96, 918.86), s = Vector3.new(488.88, 80.36, 497.41) },  -- 288 tris
		LP_0_7 = { c = Vector3.new(-2154.20, 210.68, 1399.52), s = Vector3.new(491.60, 54.46, 502.34) },  -- 288 tris
		LP_0_8 = { c = Vector3.new(-2154.75, 207.53, 1876.70), s = Vector3.new(490.49, 54.45, 496.59) },  -- 288 tris
		LP_0_9 = { c = Vector3.new(-2157.94, 236.61, 2154.03), s = Vector3.new(484.12, 44.48, 91.95) },  -- 48 tris
		LP_1_0 = { c = Vector3.new(-1682.00, 284.03, -1954.43), s = Vector3.new(498.41, 83.90, 491.14) },  -- 288 tris
		LP_1_1 = { c = Vector3.new(-1680.22, 290.95, -1482.90), s = Vector3.new(501.75, 42.60, 497.96) },  -- 288 tris
		LP_1_2 = { c = Vector3.new(-1679.91, 176.11, -999.36), s = Vector3.new(503.40, 245.48, 501.95) },  -- 288 tris
		LP_1_3 = { c = Vector3.new(-1680.45, 105.02, -520.27), s = Vector3.new(502.80, 113.80, 502.87) },  -- 288 tris
		LP_1_4 = { c = Vector3.new(-1679.09, 101.90, -40.20), s = Vector3.new(501.56, 117.35, 502.92) },  -- 288 tris
		LP_1_5 = { c = Vector3.new(-1680.61, 104.89, 439.80), s = Vector3.new(502.58, 123.33, 503.08) },  -- 288 tris
		LP_1_6 = { c = Vector3.new(-1679.74, 137.73, 921.73), s = Vector3.new(501.50, 174.92, 500.27) },  -- 288 tris
		LP_1_7 = { c = Vector3.new(-1680.92, 190.05, 1399.39), s = Vector3.new(498.62, 99.22, 502.62) },  -- 288 tris
		LP_1_8 = { c = Vector3.new(-1680.27, 233.44, 1879.53), s = Vector3.new(501.99, 39.81, 502.95) },  -- 288 tris
		LP_1_9 = { c = Vector3.new(-1676.16, 226.13, 2156.61), s = Vector3.new(487.68, 26.07, 86.78) },  -- 48 tris
		LP_2_0 = { c = Vector3.new(-1201.43, 263.75, -1955.03), s = Vector3.new(500.42, 71.49, 489.95) },  -- 288 tris
		LP_2_1 = { c = Vector3.new(-1200.77, 275.45, -1480.71), s = Vector3.new(501.75, 28.35, 499.44) },  -- 288 tris
		LP_2_2 = { c = Vector3.new(-1200.62, 152.80, -999.56), s = Vector3.new(499.01, 255.82, 502.16) },  -- 288 tris
		LP_2_3 = { c = Vector3.new(-1199.54, 43.66, -520.33), s = Vector3.new(501.85, 65.87, 503.23) },  -- 288 tris
		LP_2_4 = { c = Vector3.new(-1201.53, 32.71, -40.37), s = Vector3.new(500.78, 65.42, 502.77) },  -- 288 tris
		LP_2_5 = { c = Vector3.new(-1200.75, 36.35, 439.92), s = Vector3.new(495.07, 72.70, 502.98) },  -- 288 tris
		LP_2_6 = { c = Vector3.new(-1201.19, 112.05, 920.87), s = Vector3.new(501.10, 179.52, 499.22) },  -- 288 tris
		LP_2_7 = { c = Vector3.new(-1199.73, 202.78, 1399.63), s = Vector3.new(503.01, 134.94, 498.91) },  -- 288 tris
		LP_2_8 = { c = Vector3.new(-1200.22, 241.68, 1878.83), s = Vector3.new(501.07, 51.24, 501.35) },  -- 288 tris
		LP_2_9 = { c = Vector3.new(-1197.96, 217.51, 2155.50), s = Vector3.new(484.07, 19.68, 89.01) },  -- 48 tris
		LP_3_0 = { c = Vector3.new(-719.24, 250.58, -1955.62), s = Vector3.new(496.69, 71.06, 488.76) },  -- 288 tris
		LP_3_1 = { c = Vector3.new(-718.27, 256.49, -1479.44), s = Vector3.new(496.06, 79.18, 500.36) },  -- 288 tris
		LP_3_2 = { c = Vector3.new(-719.78, 155.62, -1000.41), s = Vector3.new(502.29, 237.37, 501.64) },  -- 288 tris
		LP_3_3 = { c = Vector3.new(-720.02, 67.53, -519.10), s = Vector3.new(503.95, 138.77, 498.66) },  -- 288 tris
		LP_3_4 = { c = Vector3.new(-719.56, 22.13, -40.43), s = Vector3.new(502.08, 50.66, 501.44) },  -- 288 tris
		LP_3_5 = { c = Vector3.new(-719.99, 68.75, 439.09), s = Vector3.new(503.97, 143.90, 500.99) },  -- 288 tris
		LP_3_6 = { c = Vector3.new(-721.10, 105.07, 919.65), s = Vector3.new(501.59, 152.14, 502.51) },  -- 288 tris
		LP_3_7 = { c = Vector3.new(-718.35, 190.85, 1399.93), s = Vector3.new(500.62, 106.15, 503.59) },  -- 288 tris
		LP_3_8 = { c = Vector3.new(-719.29, 235.81, 1879.12), s = Vector3.new(502.50, 39.37, 501.56) },  -- 288 tris
		LP_3_9 = { c = Vector3.new(-715.67, 230.21, 2156.10), s = Vector3.new(494.10, 51.92, 87.80) },  -- 48 tris
		LP_4_0 = { c = Vector3.new(-240.79, 259.16, -1954.12), s = Vector3.new(502.27, 93.17, 491.76) },  -- 288 tris
		LP_4_1 = { c = Vector3.new(-239.55, 253.53, -1480.32), s = Vector3.new(501.87, 126.62, 502.14) },  -- 288 tris
		LP_4_2 = { c = Vector3.new(-239.77, 153.38, -1000.94), s = Vector3.new(502.07, 140.30, 500.59) },  -- 288 tris
		LP_4_3 = { c = Vector3.new(-240.98, 69.13, -518.53), s = Vector3.new(499.91, 138.26, 499.10) },  -- 288 tris
		LP_4_4 = { c = Vector3.new(-241.14, 0.00, -39.57), s = Vector3.new(501.65, 0.00, 499.28) },  -- 288 tris
		LP_4_5 = { c = Vector3.new(-239.47, 53.43, 440.68), s = Vector3.new(499.98, 106.86, 502.37) },  -- 288 tris
		LP_4_6 = { c = Vector3.new(-239.89, 90.29, 920.87), s = Vector3.new(503.31, 180.59, 501.72) },  -- 288 tris
		LP_4_7 = { c = Vector3.new(-239.36, 195.65, 1399.73), s = Vector3.new(502.52, 77.49, 499.26) },  -- 288 tris
		LP_4_8 = { c = Vector3.new(-239.93, 227.87, 1878.22), s = Vector3.new(502.96, 45.17, 498.87) },  -- 288 tris
		LP_4_9 = { c = Vector3.new(-240.19, 238.30, 2154.78), s = Vector3.new(497.99, 35.75, 90.44) },  -- 48 tris
		LP_5_0 = { c = Vector3.new(238.14, 296.66, -1954.42), s = Vector3.new(495.70, 58.02, 491.15) },  -- 288 tris
		LP_5_1 = { c = Vector3.new(239.39, 255.45, -1480.81), s = Vector3.new(500.72, 146.31, 501.16) },  -- 288 tris
		LP_5_2 = { c = Vector3.new(239.27, 169.61, -1000.04), s = Vector3.new(502.26, 171.29, 500.94) },  -- 288 tris
		LP_5_3 = { c = Vector3.new(239.44, 69.88, -519.83), s = Vector3.new(501.83, 139.76, 501.21) },  -- 288 tris
		LP_5_4 = { c = Vector3.new(240.00, 0.00, -39.93), s = Vector3.new(501.77, 0.00, 502.16) },  -- 288 tris
		LP_5_5 = { c = Vector3.new(240.69, 81.32, 440.04), s = Vector3.new(496.37, 162.65, 503.27) },  -- 288 tris
		LP_5_6 = { c = Vector3.new(238.44, 83.02, 921.56), s = Vector3.new(497.42, 166.04, 500.59) },  -- 288 tris
		LP_5_7 = { c = Vector3.new(239.87, 200.30, 1398.31), s = Vector3.new(500.60, 108.48, 500.59) },  -- 288 tris
		LP_5_8 = { c = Vector3.new(240.18, 229.58, 1877.66), s = Vector3.new(501.69, 48.40, 497.80) },  -- 288 tris
		LP_5_9 = { c = Vector3.new(241.17, 248.46, 2154.35), s = Vector3.new(495.06, 46.29, 91.31) },  -- 48 tris
		LP_6_0 = { c = Vector3.new(719.39, 270.94, -1954.70), s = Vector3.new(499.76, 63.33, 490.60) },  -- 288 tris
		LP_6_1 = { c = Vector3.new(720.93, 264.46, -1480.70), s = Vector3.new(500.80, 114.34, 500.22) },  -- 288 tris
		LP_6_2 = { c = Vector3.new(719.86, 206.09, -1000.19), s = Vector3.new(503.43, 136.10, 501.95) },  -- 288 tris
		LP_6_3 = { c = Vector3.new(719.31, 81.44, -520.49), s = Vector3.new(502.33, 162.88, 502.38) },  -- 288 tris
		LP_6_4 = { c = Vector3.new(719.90, 45.23, -37.26), s = Vector3.new(503.34, 90.45, 494.99) },  -- 288 tris
		LP_6_5 = { c = Vector3.new(719.17, 87.79, 439.92), s = Vector3.new(500.61, 175.59, 503.51) },  -- 288 tris
		LP_6_6 = { c = Vector3.new(718.18, 160.53, 921.04), s = Vector3.new(498.63, 98.96, 501.89) },  -- 288 tris
		LP_6_7 = { c = Vector3.new(719.84, 196.18, 1399.94), s = Vector3.new(503.50, 85.36, 503.04) },  -- 288 tris
		LP_6_8 = { c = Vector3.new(723.12, 220.27, 1880.86), s = Vector3.new(496.11, 25.07, 501.87) },  -- 288 tris
		LP_6_9 = { c = Vector3.new(721.47, 236.85, 2154.75), s = Vector3.new(482.94, 42.40, 90.50) },  -- 48 tris
		LP_7_0 = { c = Vector3.new(1199.94, 279.01, -1954.01), s = Vector3.new(501.81, 71.51, 491.98) },  -- 288 tris
		LP_7_1 = { c = Vector3.new(1200.68, 284.29, -1479.81), s = Vector3.new(502.42, 60.95, 502.01) },  -- 288 tris
		LP_7_2 = { c = Vector3.new(1199.78, 229.56, -1001.12), s = Vector3.new(502.79, 163.68, 500.00) },  -- 288 tris
		LP_7_3 = { c = Vector3.new(1200.00, 152.74, -518.49), s = Vector3.new(502.98, 202.32, 497.90) },  -- 288 tris
		LP_7_4 = { c = Vector3.new(1200.45, 32.45, -39.43), s = Vector3.new(499.54, 64.90, 502.52) },  -- 288 tris
		LP_7_5 = { c = Vector3.new(1201.83, 111.82, 441.26), s = Vector3.new(497.36, 124.37, 501.34) },  -- 288 tris
		LP_7_6 = { c = Vector3.new(1200.68, 180.01, 919.06), s = Vector3.new(497.48, 145.85, 500.53) },  -- 288 tris
		LP_7_7 = { c = Vector3.new(1199.84, 228.04, 1399.75), s = Vector3.new(499.99, 59.44, 502.20) },  -- 288 tris
		LP_7_8 = { c = Vector3.new(1201.00, 227.73, 1881.59), s = Vector3.new(499.69, 37.06, 500.36) },  -- 288 tris
		LP_7_9 = { c = Vector3.new(1205.05, 244.04, 2154.21), s = Vector3.new(493.45, 51.78, 91.57) },  -- 48 tris
		LP_8_0 = { c = Vector3.new(1678.62, 270.08, -1954.22), s = Vector3.new(500.91, 34.99, 491.56) },  -- 288 tris
		LP_8_1 = { c = Vector3.new(1679.01, 284.99, -1480.92), s = Vector3.new(496.68, 57.56, 500.50) },  -- 288 tris
		LP_8_2 = { c = Vector3.new(1679.29, 249.69, -1000.86), s = Vector3.new(498.19, 125.55, 500.64) },  -- 288 tris
		LP_8_3 = { c = Vector3.new(1677.06, 167.52, -520.20), s = Vector3.new(497.33, 213.16, 503.06) },  -- 288 tris
		LP_8_4 = { c = Vector3.new(1678.26, 90.60, -43.42), s = Vector3.new(498.65, 77.86, 493.56) },  -- 288 tris
		LP_8_5 = { c = Vector3.new(1679.41, 118.01, 440.09), s = Vector3.new(499.30, 123.01, 500.67) },  -- 288 tris
		LP_8_6 = { c = Vector3.new(1679.99, 191.25, 919.21), s = Vector3.new(499.15, 132.56, 497.48) },  -- 288 tris
		LP_8_7 = { c = Vector3.new(1680.13, 234.28, 1398.44), s = Vector3.new(503.15, 46.95, 497.89) },  -- 288 tris
		LP_8_8 = { c = Vector3.new(1679.44, 218.98, 1880.42), s = Vector3.new(497.96, 43.47, 502.14) },  -- 288 tris
		LP_8_9 = { c = Vector3.new(1679.99, 215.97, 2154.86), s = Vector3.new(490.09, 49.80, 90.29) },  -- 48 tris
		LP_9_0 = { c = Vector3.new(2154.17, 289.09, -1954.59), s = Vector3.new(491.67, 76.53, 490.81) },  -- 288 tris
		LP_9_1 = { c = Vector3.new(2154.11, 267.43, -1480.06), s = Vector3.new(491.78, 82.67, 502.89) },  -- 288 tris
		LP_9_2 = { c = Vector3.new(2154.23, 253.56, -999.66), s = Vector3.new(491.55, 111.02, 500.52) },  -- 288 tris
		LP_9_3 = { c = Vector3.new(2154.24, 205.78, -521.95), s = Vector3.new(491.53, 200.31, 497.80) },  -- 288 tris
		LP_9_4 = { c = Vector3.new(2154.91, 190.96, -38.28), s = Vector3.new(490.19, 170.68, 498.94) },  -- 288 tris
		LP_9_5 = { c = Vector3.new(2154.91, 187.20, 440.28), s = Vector3.new(490.19, 151.51, 502.61) },  -- 288 tris
		LP_9_6 = { c = Vector3.new(2154.78, 213.58, 921.64), s = Vector3.new(490.43, 125.76, 499.16) },  -- 288 tris
		LP_9_7 = { c = Vector3.new(2154.88, 250.55, 1399.66), s = Vector3.new(490.24, 79.48, 502.02) },  -- 288 tris
		LP_9_8 = { c = Vector3.new(2155.18, 235.42, 1879.96), s = Vector3.new(489.63, 77.02, 499.05) },  -- 288 tris
		LP_9_9 = { c = Vector3.new(2155.44, 242.07, 2155.14), s = Vector3.new(489.13, 95.71, 89.72) },  -- 48 tris
	},
	-- the salt ponds: centre x, centre z, colour 1-4 (46 x 40 cells, 4-stud levees)
	ponds = {
		{ -779.0, -178.0, 2 },
		{ -779.0, -138.0, 1 },
		{ -779.0, -58.0, 3 },
		{ -779.0, -18.0, 2 },
		{ -779.0, 22.0, 1 },
		{ -779.0, 102.0, 3 },
		{ -779.0, 142.0, 2 },
		{ -779.0, 182.0, 1 },
	},
}
-- x, y, z, mesh, height
d.trees = {}
for _, n in ipairs({ "Trees1", "Trees2" }) do
	for _, t in ipairs(require(script:WaitForChild(n))) do table.insert(d.trees, t) end
end
-- the exact faceted surface: row-major (z rows, x columns), x,y,z per vertex.
-- cell (i, j) splits along p00-p11 when (i + j) is even, else along p10-p01
local v = {}
for _, n in ipairs({ "Grid1", "Grid2" }) do
	for _, x in ipairs(require(script:WaitForChild(n))) do v[#v + 1] = x end
end
d.grid = { nx = 121, nz = 111, x0 = -2400.0, z0 = -2200.0, S = 40.0, v = v }
return d
